{{- range $name, $volume := .Values.volumes }}
{{- if $volume.persistentVolumeClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $volume.persistentVolumeClaim.Name }}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $volume.persistentVolumeClaim.Size }}
  {{- with $volume.persistentVolumeClaim.StorageClassName }}
  storageClassName: {{ . }}
  {{- end }}
{{- end }}
{{- end }}
