apiVersion: v1
kind: Service
metadata:
  name: {{ include "omni.fullname" . }}-grpc
  namespace: {{ include "omni.namespace" . }}
  labels:
    {{- include "omni.labels" . | nindent 4 }}
  {{- with .Values.service.grpc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.grpc.type }}
  {{- with .Values.service.grpc.clusterIP }}
  clusterIP: {{ . | quote }}
  {{- end }}
  ports:
    - name: omni
      port: {{ .Values.service.grpc.omniPort }}
      targetPort: omni
      protocol: TCP
      appProtocol: kubernetes.io/h2c
    - name: siderolink
      port: {{ .Values.service.grpc.siderolinkApiPort }}
      targetPort: siderolink-api
      protocol: TCP
      appProtocol: kubernetes.io/h2c
  selector:
    {{- include "omni.selectorLabels" . | nindent 4 }}
