apiVersion: v1
kind: Service
metadata:
  name: {{ include "omni.fullname" . }}
  namespace: {{ include "omni.namespace" . }}
  labels:
    {{- include "omni.labels" . | nindent 4 }}
    {{- with .Values.service.main.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.main.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.main.type }}
  {{- with .Values.service.main.clusterIP }}
  clusterIP: {{ . | quote}}
  {{- end }}
  {{- if and .Values.service.main.loadBalancerIP (or (eq .Values.service.main.type "LoadBalancer")) }}
  loadBalancerIP: {{ .Values.service.main.loadBalancerIP | quote }}
  {{- end }}
  ports:
    - name: omni
      port: {{ .Values.service.main.omniPort }}
      targetPort: omni
      protocol: TCP
      appProtocol: kubernetes.io/h2c
      {{- with .Values.service.main.omniNodePort }}
      nodePort: {{ . }}
      {{- end }}
    - name: siderolink
      port: {{ .Values.service.main.siderolinkApiPort }}
      targetPort: siderolink-api
      protocol: TCP
      appProtocol: kubernetes.io/h2c
      {{- with .Values.service.main.siderolinkApiNodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "omni.selectorLabels" . | nindent 4 }}
