apiVersion: v1
kind: Service
metadata:
  name: {{ include "omni.fullname" . }}
  namespace: {{ include "omni.namespace" . }}
  labels:
    {{- include "omni.labels" . | nindent 4 }}
  {{- with .Values.service.main.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.main.type }}
  {{- with .Values.service.main.clusterIP }}
  clusterIP: {{ . | quote}}
  {{- end }}
  ports:
    - name: omni
      port: {{ .Values.service.main.omniPort }}
      targetPort: omni
      protocol: TCP
    - name: k8s-proxy
      port: {{ .Values.service.main.k8sProxyPort }}
      targetPort: k8s-proxy
      protocol: TCP
  selector:
    {{- include "omni.selectorLabels" . | nindent 4 }}
