apiVersion: v1
kind: Service
metadata:
  name: {{ include "omni.fullname" . }}-k8s-proxy
  namespace: {{ include "omni.namespace" . }}
  labels:
    {{- include "omni.labels" . | nindent 4 }}
    {{- with .Values.service.k8sProxy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.k8sProxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.k8sProxy.type }}
  {{- with .Values.service.k8sProxy.clusterIP }}
  clusterIP: {{ . | quote }}
  {{- end }}
  ports:
    - name: k8s-proxy
      port: {{ .Values.service.k8sProxy.port }}
      targetPort: k8s-proxy
      protocol: TCP
  selector:
    {{- include "omni.selectorLabels" . | nindent 4 }}
