{{- if .Values.gatewayApi.ui.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "omni.fullname" . }}-ui
  namespace: {{ include "omni.namespace" . }}
  labels:
  {{- include "omni.labels" . | nindent 4 }}
  {{- with .Values.gatewayApi.ui.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gatewayApi.ui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.gatewayApi.ui.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.gatewayApi.ui.hostnames | nindent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "omni.fullname" $ }}
          port: {{ .Values.service.main.omniPort }}
{{- end }}