apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omni.fullname" . }}-config
  namespace: {{ include "omni.namespace" . }}
  labels:
    {{- include "omni.labels" . | nindent 4 }}
stringData:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}
