{{- if .Values.ingress.kubernetesProxy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "omni.fullname" . }}-k8s-proxy
  namespace: {{ include "omni.namespace" . }}
  labels:
  {{- include "omni.labels" . | nindent 4 }}
  {{- with .Values.ingress.kubernetesProxy.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.kubernetesProxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.kubernetesProxy.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.kubernetesProxy.tls }}
  tls:
    {{- toYaml .Values.ingress.kubernetesProxy.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.kubernetesProxy.host | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "omni.fullname" $ }}-k8s-proxy
                port:
                  number: {{ .Values.service.k8sProxy.port }}
{{- end }}
