{{- if .Values.ingress.siderolinkApi.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "omni.fullname" . }}-siderolink
  namespace: {{ include "omni.namespace" . }}
  labels:
  {{- include "omni.labels" . | nindent 4 }}
  {{- with .Values.ingress.siderolinkApi.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.ingress.siderolinkApi.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.siderolinkApi.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.siderolinkApi.tls }}
  tls:
    {{- toYaml .Values.ingress.siderolinkApi.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.siderolinkApi.host | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "omni.fullname" $ }}
                port:
                  number: {{ .Values.service.main.siderolinkApiPort }}
{{- end }}
