{{- if .Values.gatewayApi.grpc.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: {{ include "omni.fullname" . }}-grpc
  namespace: {{ include "omni.namespace" . }}
  labels:
  {{- include "omni.labels" . | nindent 4 }}
  {{- with .Values.gatewayApi.grpc.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.gatewayApi.grpc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.gatewayApi.grpc.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.gatewayApi.grpc.hostnames | nindent 4 }}
  rules:
    - matches:
        - method:
            service: omni.resources.ResourceService
        - method:
            service: oidc.OIDCService
        - method:
            service: management.ManagementService
        - method:
            service: auth.AuthService
        - method:
            service: cosi.resource.State
      backendRefs:
        - name: {{ include "omni.fullname" $ }}-grpc
          port: {{ .Values.service.grpc.omniPort }}
{{- end }}